import "./globals.css";
import Header from "@/customComponents/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-gray-50 text-gray-900">
        <Header />
        {children}
      </body>
    </html>
  );
}
